"""add phase9 security columns

Revision ID: 3d4ba7631c35
Revises: 430c4673ff77
Create Date: 2026-08-16 13:07:41.394940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4ba7631c35'
down_revision: Union[str, Sequence[str], None] = '430c4673ff77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('used', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('postgres_connections', sa.Column('allowed_databases', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('verification_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_token_hash')
    op.drop_column('postgres_connections', 'allowed_databases')
    op.drop_column('password_reset_tokens', 'used')
    # ### end Alembic commands ###
